<a href="https://colab.research.google.com/github/subhashchandra630/Machine-Learning/blob/main/liner_regression_without_sklearn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


In [2]:
from google.colab import files
upload=files.upload()

Saving automobileEDA.csv to automobileEDA.csv


In [3]:
path='automobileEDA.csv'
df=pd.read_csv(path)
df.head()

symboling  normalized-losses         make aspiration num-of-doors  \
0          3                122  alfa-romero        std          two   
1          3                122  alfa-romero        std          two   
2          1                122  alfa-romero        std          two   
3          2                164         audi        std         four   
4          2                164         audi        std         four   

    body-style drive-wheels engine-location  wheel-base    length  ...  \
0  convertible          rwd           front        88.6  0.811148  ...   
1  convertible          rwd           front        88.6  0.811148  ...   
2    hatchback          rwd           front        94.5  0.822681  ...   
3        sedan          fwd           front        99.8  0.848630  ...   
4        sedan          4wd           front        99.4  0.848630  ...   

   compression-ratio  horsepower  peak-rpm city-mpg highway-mpg  price  \
0                9.0       111.0    5000.0       21          27  13495   
1                9.0       111.0    5000.0       21          27  16500   
2                9.0       154.0    5000.0       19          26  16500   
3               10.0       102.0    5500.0       24          30  13950   
4                8.0       115.0    5500.0       18          22  17450   

  city-L/100km  horsepower-binned  diesel  gas  
0    11.190476             Medium       0    1  
1    11.190476             Medium       0    1  
2    12.368421             Medium       0    1  
3     9.791667             Medium       0    1  
4    13.055556             Medium       0    1  

[5 rows x 29 columns]


**Maths behind multi linear regression**

In [4]:
x = np.array([[1, 110, 40], [1, 120, 30] , [1, 100, 20], [1, 90, 0], [1, 80, 10]])
x

array([[  1, 110,  40],
       [  1, 120,  30],
       [  1, 100,  20],
       [  1,  90,   0],
       [  1,  80,  10]])

In [5]:
y = np.array([[100], [90], [80], [70], [60]])  

In [6]:
x_trans=x.transpose()

In [7]:
xmulti=np.matmul(x_trans,x)

In [8]:
xmulti

array([[    5,   500,   100],
       [  500, 51000, 10800],
       [  100, 10800,  3000]])

In [9]:
xinv=np.linalg.inv(xmulti)

In [10]:
xinv

array([[ 2.02000000e+01, -2.33333333e-01,  1.66666667e-01],
       [-2.33333333e-01,  2.77777778e-03, -2.22222222e-03],
       [ 1.66666667e-01, -2.22222222e-03,  2.77777778e-03]])

In [11]:
finalx=np.matmul(xinv,x_trans)

In [12]:
b=np.matmul(finalx,y)

In [13]:
b

array([[20. ],
       [ 0.5],
       [ 0.5]])

**Multi regression on automobile eda data set**

In [14]:
Z=df[['horsepower','curb-weight','engine-size','highway-mpg']]

In [15]:
featureset = df[['horsepower', 'curb-weight', 'engine-size', 'highway-mpg']]

In [16]:
from sklearn.preprocessing import MinMaxScaler
x = featureset.values #returns a numpy array
min_max_scaler = MinMaxScaler()
feature_mtx = min_max_scaler.fit_transform(x)
Z = feature_mtx
feature_mtx [0:5]

array([[0.29439252, 0.41117145, 0.26037736, 0.28947368],
       [0.29439252, 0.41117145, 0.26037736, 0.28947368],
       [0.4953271 , 0.51784329, 0.34339623, 0.26315789],
       [0.25233645, 0.32932506, 0.18113208, 0.36842105],
       [0.31308411, 0.51823119, 0.28301887, 0.15789474]])

In [17]:
from sklearn.preprocessing import MinMaxScaler
x = np.array(df[['price']]) #returns a numpy array
min_max_scaler = MinMaxScaler()
feature_mtx = min_max_scaler.fit_transform(x)
df[['price']] = feature_mtx
feature_mtx [0:5]

array([[0.20795889],
       [0.28255797],
       [0.28255797],
       [0.21925426],
       [0.3061417 ]])

In [18]:
x=Z

In [19]:
x.shape

(201, 4)

In [20]:
col=np.ones((201,1))

In [21]:
x=np.append(col,x,axis=1)

In [23]:
x.shape

(201, 5)

In [24]:
y=df[['price']]

In [25]:
x=np.array(x)

In [26]:
y=np.array(y)

In [27]:
x_trans=x.transpose()

In [29]:
xmulti=np.matmul(x_trans,x)

In [30]:
xinv=np.linalg.inv(xmulti)

In [31]:
finalx=np.matmul(xinv,x_trans)

In [32]:
b=np.matmul(finalx,y)

In [33]:
b


array([[-0.14402224],
       [ 0.28419863],
       [ 0.30128725],
       [ 0.53635668],
       [ 0.03401481]])